FROM node:16.3.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

CMD npm config set cache-min 9999999 && \
    npm install && \
    npx wait-port rabbit:5672 && \
    npm run start:dev
