version: '3'
services:
  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "8080:80"
    environment:
      - PORT=80
    restart: "no"
  file-storage-gateway-service:
    build: ./fileStorageGatewayService
    container_name: file-storage-gateway-service
    ports:
      - "8081:81"
    environment:
      - PORT=81
    restart: "no"
