version: '3'
services:
  db:
    image: mongo:4.2.8
    ports:
      - "4000:27017"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test

  rabbit:
    image: rabbitmq:3.11.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - app-network
    restart: on-failure

  signaling-service:
    build:
      context: ./signalingService
      dockerfile: Dockerfile-dev
    volumes:
      - ./signalingService/src:/usr/src/app/src:z
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=signalingData
    networks:
      - app-network
    restart: "no"
    depends_on:
      - rabbit

  user-service:
    build:
      context: ./userService
      dockerfile: Dockerfile-dev
    volumes:
      - ./userService/src:/usr/src/app/src:z
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    networks:
      - app-network
    restart: "no"
    depends_on:
      - rabbit
      - db

  query-service:
    build:
      context: ./queryService
      dockerfile: Dockerfile-dev
    volumes:
      - ./queryService/src:/usr/src/app/src:z
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=queryData
      - RABBIT=amqp://guest:guest@rabbit:5672
    networks:
      - app-network
    restart: "no"
    depends_on:
      - rabbit

networks:
  app-network:
    driver: bridge

#  file-storage-gateway-service:
#    build: ./fileStorageGatewayService
#    container_name: file-storage-gateway-service
#    ports:
#      - "8082:80"
#    environment:
#      - PORT=80
#      - YSTORAGE_ACCESS_KEY_ID=${YSTORAGE_ACCESS_KEY_ID}
#      - YSTORAGE_SECRET_ACCESS_KEY_ID=${YSTORAGE_SECRET_ACCESS_KEY_ID}
#    restart: "no"
