version: '3'
services:
  db:
    image: mongo:4.2.8
    ports:
      - "4000:27017"
    restart: on-failure

  rabbit:
    image: rabbitmq:3.11.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - app-network
    restart: on-failure

  signaling-service:
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=signalingService
      - RABBIT=amqp://guest:guest@rabbit:5672
    networks:
      - app-network
    restart: "no"
    depends_on:
      - rabbit

  query-service:
    build:
      context: ./queryService
      dockerfile: Dockerfile-dev
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=queryService
      - RABBIT=amqp://guest:guest@rabbit:5672
    networks:
      - app-network
    restart: "no"
    depends_on:
      - rabbit

networks:
  app-network:
    driver: bridge

