version: '3'
services:
  db:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - app-network

  rabbit:
    image: rabbitmq:3.11.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - app-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  signaling-service:
    image: cr.yandex/crplh29k6e12da83i0ac/signalling-service:latest
    ports:
      - "81:8080"
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=signalingService
      - RABBIT=amqp://guest:guest@rabbit:5672
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - rabbit

  query-service:
    image: cr.yandex/crplh29k6e12da83i0ac/query-service:latest
    ports:
      - '80:8080'
    environment:
      - PORT=8080
      - DB_HOST=mongodb://db:27017
      - DB_NAME=queryService
      - RABBIT=amqp://guest:guest@rabbit:5672
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - rabbit

networks:
  app-network:
    driver: bridge

