on: 
  push:
    branches: ["master"]

env:
  YCR_SERVER: cr.yandex
  YCR_REGISTRY_ID: ${{ secrets.YCR_REGISTRY_ID }}
  YCR_USERNAME: oauth
  YCR_PASSWORD: ${{ secrets.YCR_PASSWORD }}

jobs:

  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Yandex Container Registry
        run: |
          echo "${{ env.YCR_PASSWORD }}" | tr -d '\n' | docker login -u "${{ env.YCR_USERNAME }}" --password-stdin "${{ env.YCR_SERVER }}"

      - name: Build Query Service Docker image
        working-directory: ./services/queryService
        run: |
            docker build -t "${{ env.YCR_SERVER }}/${{ env.YCR_REGISTRY_ID }}/query-service:${{ github.sha }}" -f "Dockerfile-prod" .
      - name: Push Query Service image to Yandex Container Registry
        run: |
          docker push "${{ env.YCR_SERVER }}/${{ env.YCR_REGISTRY_ID }}/query-service:${{ github.sha }}"

      - name: Build Signalling Service Docker image
        working-directory: ./services/signalingService
        run: |
          docker build -t "${{ env.YCR_SERVER }}/${{ env.YCR_REGISTRY_ID }}/signalling-service:${{ github.sha }}" -f "Dockerfile-prod" .
      - name: Push Query Service image to Yandex Container Registry
        run: |
          docker push "${{ env.YCR_SERVER }}/${{ env.YCR_REGISTRY_ID }}/signalling-service:${{ github.sha }}"