on: 
  push:
    branches: ["master"]

env:
  YCR_USERNAME: oauth
  YCR_PASSWORD: ${{ secrets.YCR_PASSWORD }}

jobs:

  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Yandex Container Registry
        run: echo -n "${{ env.YCR_PASSWORD}}" | docker login --username oauth --password-stdin "${{ env.YCR_PASSWORD }}" cr.yandex
      
